### ISSUE TITLE
Remove hidden file

### ISSUE THREAD

**Issue by datawookie** [jlee66/airbnb#14]
The file `.Rapp.history` in the `R/` folder should not be part of your repository.

**Comment by jlee66** [comment]
remove hidden file issue resolved

**Comment by datawookie** [comment]
I see that there are hidden files in the root folder too!

**Comment by jlee66** [comment]
removed .Rapp.history in the data/folder issue resolved.

**Comment by datawookie** [comment]
Thanks!
